import { img } from './photos';

/**
 * Textes alternatifs anglais des portfolios Mariage et Portrait et des bandeaux.
 * Traduits des alts officiels de Sam (photos.ts) ; mêmes règles qu'en français :
 * les mariés ne sont jamais nommés, les personnes photographiées non plus tant que
 * leur accord n'est pas confirmé.
 *
 * Les autres pages anglaises portent leurs alts en ligne, à côté de leurs images.
 */
export const ALT_EN: Record<string, string> = {
  // ————— mariage —————
  'baiser-balustrade-noir-et-blanc-palais-royal-paris': 'A kiss at the balustrade, black and white, Palais-Royal, Paris',
  'baiser-coucher-de-soleil-parc-chateau-champlatreux': 'A kiss at sunset in the park, veil spread over the grass, château de Champlâtreux',
  'baiser-cou-tatouage-noir-et-blanc-mariage-loiret': 'A kiss on the neck, a tattoo on the shoulder, black and white, a wedding in the Loiret',
  'baiser-mains-visage-jardins-coppelia-honfleur': 'A kiss, her hands on the groom’s face, Coppélia gardens',
  'baiser-mariee-portee-contre-jour-dore-jardins-coppelia-honfleur': 'A kiss, the bride held aloft against the golden backlight, Coppélia gardens near Honfleur',
  'baiser-pavillon-colbert-louvre-paris': 'A kiss in front of the Colbert pavilion of the Louvre, black and white',
  'baiser-renverse-piste-verriere-chateau-pont-chevron': 'A dip and a kiss on the dance floor beneath the glass roof, château du Pont-Chevron',
  'baiser-salon-boiseries-noir-et-blanc-chateau-champlatreux': 'A kiss in the panelled drawing room among old portraits, black and white, château de Champlâtreux',
  'ceremonie-applaudissements-chateau-saint-martin-du-tertre': 'Applause during the ceremony, château de Saint-Martin-du-Tertre',
  'ceremonie-houppa-parc-chateau-baronville-beville-le-comte': 'Ceremony beneath the chuppah in the park of the château de Baronville',
  'complicite-pere-mariee-jardins-coppelia-honfleur': 'A high five between the bride and her father, black and white, Coppélia gardens',
  'cortege-demoiselles-d-honneur-portes-anciennes-chateau-pont-chevron': 'The bridesmaids’ procession and the bride before the old doors, château du Pont-Chevron, Ouzouer-sur-Trézée',
  'couple-arcades-louvre-paris': 'The couple beneath the arcades of the Louvre, golden light, Paris',
  'couple-banc-jardin-paris': 'The couple on a bench in a Paris garden, black and white',
  'danse-tendre-chateau-pont-chevron-ouzouer-sur-trezee': 'A tender dance at the château du Pont-Chevron in the Loire Valley',
  'detail-bouquet-mains-maries-chateau-champlatreux': 'Detail of the hydrangea bouquet and the couple’s hands, château de Champlâtreux',
  'detail-mains-robe-jardins-coppelia-honfleur': 'Detail of hands on the gown, black and white, Coppélia gardens',
  'details-papeterie-mariage-chateau-champlatreux': 'The wedding stationery laid on the edge of the billiard table, château de Champlâtreux',
  'etreinte-galerie-palais-royal-paris': 'An embrace in the bright gallery of the Palais-Royal, Paris',
  'etreinte-maries-noir-et-blanc': 'The couple embracing, black and white',
  'etreinte-reflet-miroir-ancien-chateau-champlatreux': 'The couple’s embrace reflected in an antique mirror, château de Champlâtreux',
  'etreinte-voile-noir-et-blanc-jardins-coppelia-honfleur': 'The couple embracing, black and white, Coppélia gardens',
  'facade-chateau-champlatreux-maries-fenetre-et-perron': 'The façade of the château de Champlâtreux, the groom on the front steps and the bride at the window',
  'feu-d-artifice-maries-parc-chateau-champlatreux': 'The couple before the fireworks over the park, château de Champlâtreux',
  'front-contre-front-lumiere-doree-chateau-champlatreux': 'Forehead to forehead in the golden evening light, château de Champlâtreux',
  'grand-escalier-entree-maries-chateau-saint-martin-du-tertre': 'The couple entering down the grand staircase of a French château',
  'houppa-crepuscule-chateau-la-bourdaisiere-montlouis-sur-loire': 'Ceremony beneath the chuppah at dusk, château de la Bourdaisière, Loire Valley',
  'invite-reflets-diner-chateau-saint-martin-du-tertre': 'A guest’s face through the reflections of the dinner, château de Saint-Martin-du-Tertre',
  'larmes-mariee-noir-et-blanc-jardins-coppelia-honfleur': 'The bride’s tears, black and white, Coppélia gardens',
  'mains-bouquet-noir-et-blanc-high-key-royan': 'The couple’s hands on the bouquet, high-key black and white, Royan',
  'marie-porte-fete-jardins-coppelia-honfleur': 'The groom carries the bride during the party, Coppélia gardens near Honfleur',
  'marie-porte-mariee-plage-noir-et-blanc-santa-giulia-corse': 'The groom carries the bride along Santa Giulia beach, black and white, Porto-Vecchio, Corsica',
  'marie-porte-mariee-terrasse-coucher-de-soleil-jardins-coppelia-honfleur': 'The groom carries the bride across the terrace at sunset, Coppélia gardens near Honfleur',
  'marie-porte-mariee-voile-au-vent-allee-chateau-champlatreux': 'The groom carries the bride down the avenue, veil caught by the wind, château de Champlâtreux',
  'mariee-a-cheval-parc-fontaine-chateau-champlatreux': 'The bride on horseback in the park, near the fountain, château de Champlâtreux',
  'mariee-baiser-mere-marrakech': 'The bride kisses her mother, Marrakech',
  'mariee-bassin-palmiers-marrakech': 'The bride beside the great palm-lined pool, Marrakech',
  'mariee-bouquet-profil-rideaux-chateau-champlatreux': 'The bride in profile, bouquet in hand, between the drawing-room curtains, château de Champlâtreux',
  'mariee-colonnade-lanternes-palais-royal-paris': 'Bride alone beneath the colonnade and lanterns of the Palais-Royal',
  'mariee-chapeau-cape-balustrade-palais-royal-paris': 'The bride in a hat, cape spread across the balustrade, Palais-Royal',
  'mariee-chaussures-lumiere-rayee-noir-et-blanc-mariage-loiret': 'The bride fastening her shoes in striped light, black and white, a wedding in the Loiret',
  'mariee-chignon-profil-porte-chateau-champlatreux': 'The bride in profile, hair in a high chignon, framed by a doorway, château de Champlâtreux',
  'mariee-dentelle-fenetre-lumiere-matin': 'The bride in lace by the window, morning light',
  'mariee-dos-nu-fenetre-parc-chateau-champlatreux': 'The bride from behind, facing the window open onto the park, château de Champlâtreux',
  'mariee-dos-voile-grande-fenetre-parc-chateau-champlatreux': 'The bride from behind, beneath her veil, before the tall window open onto the park, château de Champlâtreux',
  'mariee-escalier-pierre-rampe-fer-forge-chateau-champlatreux': 'The bride on the stone staircase with its wrought-iron banister, château de Champlâtreux',
  'mariee-fenetre-traine-chateau-champlatreux': 'Bride at a window, train spread across the parquet of a French château',
  'mariee-marche-parc-chateau-saint-martin-du-tertre': 'The bride crossing the park, black and white, château de Saint-Martin-du-Tertre',
  'mariee-marches-mouvement-chateau-saint-martin-du-tertre': 'The bride climbing the steps, gown in motion, château de Saint-Martin-du-Tertre',
  'mariee-profil-galerie-palais-royal-paris': 'The bride in profile in the gallery of the Palais-Royal, Paris',
  'mariee-silhouette-porte-fenetre-hotel-normandy-deauville': 'The bride in silhouette at the French window open onto the balcony, Hôtel Barrière Le Normandy, Deauville',
  'mariee-sourire-voile-jardin-grand-courtoiseau-loiret': 'Bride smiling beneath her veil, gardens of the Grand Courtoiseau, Loiret',
  'mariee-sous-le-voile-dentelle-chateau-champlatreux': 'The bride beneath her lace veil, hand on her ring, château de Champlâtreux',
  'mariee-terrasse-haie-lumiere-du-soir-jardins-coppelia-honfleur': 'The bride walking along the hedge on the terrace, evening light, Coppélia gardens near Honfleur',
  'mariee-traine-grand-salon-parquet-chateau-champlatreux': 'The bride and her train in the grand salon, the groom at the window, château de Champlâtreux',
  'mariee-voile-dentelle-contre-jour-chateau-champlatreux': 'Portrait of the bride in a lace veil, backlit at the window, château de Champlâtreux',
  'mariee-voile-fenetre-preparatifs-chateauneuf-sur-loire': 'The bride beneath her veil at the window during the preparations, Châteauneuf-sur-Loire',
  'maries-baiser-devant-facade-chateau-champlatreux': 'The couple kissing before the façade of the château de Champlâtreux',
  'maries-colonnade-pont-bir-hakeim-paris': 'The couple within the colonnade of the pont de Bir-Hakeim, Paris',
  'maries-crepuscule-parc-voile-chateau-champlatreux': 'The couple walking away through the park at dusk, veil spread behind, château de Champlâtreux',
  'maries-embrasure-fenetre-sol-damier-chateau-champlatreux': 'The couple in a window recess, chequered floor, château de Champlâtreux',
  'maries-fenetre-facade-chateau-saint-martin-du-tertre': 'The couple at a window of the façade, château de Saint-Martin-du-Tertre, Val-d’Oise',
  'maries-front-contre-front-chateau-saint-martin-du-tertre': 'Forehead to forehead, black and white, château de Saint-Martin-du-Tertre',
  'maries-grand-escalier-chateau-de-la-fontaine-griselles': 'The bride on the grand staircase and the groom at the window, château de la Fontaine in Griselles, Loiret',
  'maries-jardin-a-la-francaise-noir-et-blanc-chateau-pont-chevron': 'The couple in the formal French garden, black and white, château du Pont-Chevron',
  'maries-jeu-d-ombre-couloir': 'The couple caught in a play of light and shadow at the end of a corridor',
  'maries-lumiere-de-lampe-robe-dentelle': 'The couple in the warm light of a lamp, a high-necked lace gown',
  'maries-mains-liees-contre-plongee-escalier-chateau-champlatreux': 'The couple hand in hand, seen from below on the staircase, château de Champlâtreux',
  'maries-nef-eglise-sainte-jeanne-d-arc-gien-noir-et-blanc': 'The couple walking up the nave of the church of Sainte-Jeanne-d’Arc in Gien, train and veil spread, black and white',
  'maries-parc-bras-leve-joie-chateau-champlatreux': 'The couple crossing the park, an arm raised in joy, château de Champlâtreux',
  'maries-plage-baie-santa-giulia-corse': 'The couple alone facing the bay of Santa Giulia',
  'maries-pont-bir-hakeim-tour-eiffel-paris': 'The couple on the pont de Bir-Hakeim facing the Eiffel Tower, black and white',
  'maries-rochers-ciel-orage-plage-ramatuelle-saint-tropez': 'The couple on the rocks facing the sea under a storm sky, Ramatuelle beach near Saint-Tropez',
  'maries-rochers-mer-domaine-murtoli-corse': 'The couple on the rocks facing the sea, Domaine de Murtoli, Corsica',
  'portrait-mariee-lumiere-doree-chateau-champlatreux': 'Portrait of the bride in golden light, château de Champlâtreux',
  'portrait-mariee-lumiere-doree-jardins-coppelia-honfleur': 'Portrait of the bride in golden light, Coppélia gardens near Honfleur',
  'premiere-danse-chateau-la-bourdaisiere': 'First dance at the château de la Bourdaisière',
  'preparatifs-chaussures-dior-chateau-champlatreux': 'The bride’s Dior heels during the preparations, château de Champlâtreux',
  'preparatifs-maquillage-regard-chateau-champlatreux': 'Preparations: eye make-up, a close-up of the bride’s gaze, château de Champlâtreux',
  'preparatifs-mariee-voile-clair-obscur-deauville': 'The bride beneath her veil during the preparations, chiaroscuro, Deauville',
  'preparatifs-mere-ajuste-voile-chateau-pont-chevron-ouzouer-sur-trezee': 'Her mother adjusts the bride’s veil during the preparations, château du Pont-Chevron, Ouzouer-sur-Trézée',
  'profil-halo-lumiere-jardins-coppelia-honfleur': 'A profile in a halo of light, Coppélia gardens near Honfleur',
  'regards-complices-maries-noir-et-blanc-chateau-champlatreux': 'A knowing look between the couple, black and white, château de Champlâtreux',
  'rire-pere-mariee-bouquet-noir-et-blanc-chateau-pont-chevron': 'The father laughing before the bride and her bouquet, black and white, château du Pont-Chevron',
  'rires-maries-jardins-coppelia-honfleur': 'The couple laughing face to face, Coppélia gardens, black and white',
  'rires-maries-lumiere-doree-parc-chateau-champlatreux': 'The couple laughing in the golden light of the park, château de Champlâtreux',
  'robe-mouvement-escalier-chateau-champlatreux': 'The gown in motion on the staircase of the château de Champlâtreux',
  'seance-jour-d-apres-vagues-deauville': 'Day-after session in the waves at Deauville, black and white',
  'soiree-baiser-piste-chateau-saint-martin-du-tertre': 'A kiss on the dance floor, château de Saint-Martin-du-Tertre, Val-d’Oise',
  'soiree-etreinte-piste-jardins-coppelia-honfleur': 'An embrace on the dance floor, Coppélia gardens',
  'sortie-eglise-petales-reportage-mariage': 'Leaving the church beneath the petals, black and white',
  'sortie-maries-voile-petales-jardins-coppelia-honfleur': 'The couple leaving under a shower of petals, veil in the wind, Honfleur',
  'tendresse-banc-jardin-paris': 'Tenderness on a bench in a Paris garden, black and white',
  'voile-parc-chateau-pont-chevron-noir-et-blanc': 'Veil unfurled in the park of the château du Pont-Chevron, black and white',

  // ————— portrait —————
  'detail-main-bracelets-portrait-art-ame': 'Detail of a hand and its bracelets during a Portrait: Art & Âme session',
  'detail-main-penombre-portrait': 'Detail of a hand in low light during a portrait session',
  'detail-mains-croisees-noir-et-blanc': 'Crossed hands, detail in black and white',
  'portrait-armonie-noury-miss-loiret-noir-et-blanc': 'Official studio portrait, black and white',
  'portrait-art-ame-larme-essuyee': 'A tear wiped away during a Portrait: Art & Âme session',
  'portrait-art-ame-lumiere-laterale-studio-gien': 'Portrait in side light at the Gien studio, black and white',
  'portrait-art-ame-main-visage-noir-et-blanc': 'Portrait with a hand against the face, frontal gaze, black and white',
  'portrait-art-ame-miroir-rond': 'Reflection in a round mirror during a portrait session',
  'portrait-art-ame-pensive-fond-peint': 'Pensive portrait seated against a painted backdrop',
  'portrait-art-ame-regard-leve-noir-et-blanc': 'Eyes lifted towards the light, portrait in black and white',
  'portrait-art-ame-silhouette-fenetre-lampe': 'Silhouette seated by a window, a lamp glowing in the dark',
  'portrait-art-ame-sourire-fond-peint': 'A held-back smile, portrait against a painted backdrop',
  'portrait-cheveux-regard-baisse-noir-et-blanc': 'Hair in the light, eyes lowered, portrait in black and white',
  'portrait-homme-chapeau-melon-studio-gien': 'Portrait of a man in a bowler hat and round glasses, Gien studio',
  'portrait-homme-exterieur-brique-portail': 'Portrait of a man outdoors against brick and a green gate',
  'portrait-homme-lin-drape-clair': 'Portrait of a man in a linen shirt against a pale drape',
  'portrait-jade-allongee-chesterfield-cocktail-studio-gien': 'Lying on the chesterfield, burgundy dress and cocktail, Gien studio',
  'portrait-jade-beret-chesterfield-studio-gien': 'Beret and navy dress on the chesterfield, Gien studio',
  'portrait-jade-chesterfield-vinyles-ambiance-studio-gien': 'On the chesterfield, turntable and records, the hushed mood of the Gien studio',
  'portrait-jade-fauteuil-cuir-lampe-industrielle-studio-gien': 'In the leather armchair beneath the industrial lamp, Gien studio',
  'portrait-jade-lecture-fenetre-rue-noir-et-blanc-studio-gien': 'Reading at the window open onto the street, black and white, Gien studio',
  'portrait-jade-profil-beret-mur-vert-studio-gien': 'In profile, a pale beret against a green wall, Gien studio',
  'portrait-jade-reflet-miroir-rond-beret-studio-gien': 'Reflection in the round mirror, beret and red lips, Gien studio',
  'portrait-justine-bourrelier-costume-sombre-studio-gien': 'Portrait in a dark suit on a leather armchair, Gien studio',
  'portrait-justine-bourrelier-drape-ivoire-studio-gien': 'Portrait against an ivory drape, Gien studio',
  'portrait-justine-bourrelier-mains-visage-studio-gien': 'Portrait, hands framing the face, Gien studio',
  'portrait-justine-bourrelier-robe-studio-gien': 'Portrait in an embroidered dress with a feather, Gien studio',
  'portrait-maelle-menotti-art-ame-chesterfield': 'Portrait seated on a chesterfield sofa, Portrait: Art & Âme session',
  'portrait-maelle-menotti-noir-et-blanc-scene': 'Portrait in black and white under stage light',
  'portrait-maelle-menotti-sequins-lumiere-fenetre': 'Portrait in a sequinned top in the light of a window',
  'portrait-main-pudeur-noir-et-blanc': 'A hand raised before the face, portrait in black and white',
  'portrait-nicolas-vicquenault-pianiste-jazz': 'Portrait of a jazz pianist at his instrument',
  'portrait-nikita-dj-voilage-fenetre': 'Portrait behind a window curtain',
  'portrait-noir-et-blanc-ombre-mur-studio-gien': 'Arm raised and shadow cast on the wall, black and white, Gien studio',
  'portrait-noir-et-blanc-regard-epaule-marseille': 'A look over the shoulder, black and white, Marseille',
  'portrait-olivia-maquillage-levres-coulisses-noir-et-blanc': 'Lip make-up backstage, black and white',
  'portrait-olivia-profil-sourire-coulisses-paris': 'In profile, a smile backstage, Paris',
  'portrait-olivia-regard-clair-obscur-noir-et-blanc': 'A gaze in chiaroscuro, black and white',
  'portrait-olivia-robe-blanche-colonne-noir-et-blanc-palais-royal-paris': 'An embroidered white dress against a column, black and white, Palais-Royal, Paris',
  'portrait-olivia-robe-blanche-colonnes-palais-royal-paris': 'An embroidered white dress between the columns, Palais-Royal, Paris',
  'portrait-olivia-robe-blanche-mouvement-colonnade-palais-royal-paris': 'A white dress lifting in the colonnade of the Palais-Royal, Paris',
  'portrait-olivia-robe-rouge-dentelle-grilles-palais-royal-paris': 'A red lace dress before the gilded railings of the Palais-Royal, Paris',
  'portrait-olivia-robe-rouge-mouvement-galerie-palais-royal-paris': 'A red dress in motion in the gallery of the Palais-Royal, Paris',
  'portrait-profil-penombre': 'Profile sculpted by shadow',
  'portrait-rire-chesterfield-mur-vert': 'Open laughter on a chesterfield sofa against a green wall',
  'portrait-robe-bleue-satin-studio-gien': 'Portrait in a blue satin dress, Gien studio',
  'portrait-robe-noire-salon-chateau-de-villette': 'Portrait in a black dress in the drawing room of a French château',
  'portrait-tabouret-fond-clair-studio-gien': 'Portrait seated on a stool against a pale backdrop, Gien studio',
  'robe-blanche-mouvement-escalier-noir-et-blanc': 'White dress in movement on a staircase, black and white',
};

const cle = (fichier: string) => fichier.replace(/-nathanael-charpentier\.jpg$/, '');

/** Texte alternatif anglais d'une image par son nom de fichier. */
export function altEn(fichier: string): string {
  const texte = ALT_EN[cle(fichier)];
  if (!texte) throw new Error(`English alt missing: ${fichier}`);
  return texte;
}

/** Raccourci galerie anglaise : [{ img, alt }] à partir d'une liste de noms de fichiers. */
export function galerieEn(fichiers: string[]) {
  return fichiers.map((f) => ({ img: img(f), alt: altEn(f) }));
}
