/**
 * Ordre des portfolios Mariage et Portrait · note de Sam du 18 septembre 2026
 * (scripts/ordre-portfolios-2026-09-18.md). Une seule source pour le français et l'anglais :
 * les deux versions affichent exactement les mêmes images, dans le même ordre.
 *
 * Chaque entrée : [fichier, sélection courte ★]. La page affiche tout, dans l'ordre.
 * Le ★ servira si l'on passe un jour à un « voir plus ».
 */

// 93 images dans la note ; La Palmyre en est retirée, à la demande de Nathanaël.
export const ORDRE_MARIAGE: [string, boolean][] = [
  ['marie-porte-mariee-voile-au-vent-allee-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['voile-parc-chateau-pont-chevron-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['maries-crepuscule-parc-voile-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['mariee-dos-voile-grande-fenetre-parc-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['sortie-maries-voile-petales-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['mariee-bassin-palmiers-marrakech-nathanael-charpentier.jpg', true],
  ['portrait-mariee-lumiere-doree-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['facade-chateau-champlatreux-maries-fenetre-et-perron-nathanael-charpentier.jpg', true],
  ['details-papeterie-mariage-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['preparatifs-chaussures-dior-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['preparatifs-maquillage-regard-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-voile-fenetre-preparatifs-chateauneuf-sur-loire-nathanael-charpentier.jpg', true],
  ['preparatifs-mere-ajuste-voile-chateau-pont-chevron-ouzouer-sur-trezee-nathanael-charpentier.jpg', true],
  ['mariee-dentelle-fenetre-lumiere-matin-nathanael-charpentier.jpg', false],
  ['mariee-sous-le-voile-dentelle-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-chaussures-lumiere-rayee-noir-et-blanc-mariage-loiret-nathanael-charpentier.jpg', false],
  ['mariee-fenetre-traine-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['mariee-dos-nu-fenetre-parc-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['preparatifs-mariee-voile-clair-obscur-deauville-nathanael-charpentier.jpg', false],
  ['mariee-voile-dentelle-contre-jour-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['grand-escalier-entree-maries-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', true],
  ['ceremonie-houppa-parc-chateau-baronville-beville-le-comte-nathanael-charpentier.jpg', false],
  ['ceremonie-applaudissements-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', true],
  ['houppa-crepuscule-chateau-la-bourdaisiere-montlouis-sur-loire-nathanael-charpentier.jpg', false],
  ['maries-nef-eglise-sainte-jeanne-d-arc-gien-noir-et-blanc-nathanael-charpentier.jpg', false],
  ['sortie-eglise-petales-reportage-mariage-nathanael-charpentier.jpg', true],
  ['cortege-demoiselles-d-honneur-portes-anciennes-chateau-pont-chevron-nathanael-charpentier.jpg', false],
  ['complicite-pere-mariee-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['rire-pere-mariee-bouquet-noir-et-blanc-chateau-pont-chevron-nathanael-charpentier.jpg', true],
  ['mariee-baiser-mere-marrakech-nathanael-charpentier.jpg', false],
  ['maries-jeu-d-ombre-couloir-nathanael-charpentier.jpg', true],
  ['maries-lumiere-de-lampe-robe-dentelle-nathanael-charpentier.jpg', false],
  ['maries-jardin-a-la-francaise-noir-et-blanc-chateau-pont-chevron-nathanael-charpentier.jpg', true],
  ['baiser-coucher-de-soleil-parc-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['maries-embrasure-fenetre-sol-damier-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['maries-mains-liees-contre-plongee-escalier-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['maries-grand-escalier-chateau-de-la-fontaine-griselles-nathanael-charpentier.jpg', false],
  ['maries-parc-bras-leve-joie-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['rires-maries-lumiere-doree-parc-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['front-contre-front-lumiere-doree-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-marche-parc-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', false],
  ['maries-front-contre-front-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', false],
  ['mariee-marches-mouvement-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', false],
  ['regards-complices-maries-noir-et-blanc-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-chignon-profil-porte-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-bouquet-profil-rideaux-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mariee-traine-grand-salon-parquet-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['etreinte-reflet-miroir-ancien-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['baiser-salon-boiseries-noir-et-blanc-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['maries-baiser-devant-facade-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['maries-fenetre-facade-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', true],
  ['mariee-escalier-pierre-rampe-fer-forge-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['robe-mouvement-escalier-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['mariee-a-cheval-parc-fontaine-chateau-champlatreux-nathanael-charpentier.jpg', true],
  ['mariee-sourire-voile-jardin-grand-courtoiseau-loiret-nathanael-charpentier.jpg', false],
  ['mariee-chapeau-cape-balustrade-palais-royal-paris-nathanael-charpentier.jpg', true],
  ['couple-arcades-louvre-paris-nathanael-charpentier.jpg', false],
  ['etreinte-galerie-palais-royal-paris-nathanael-charpentier.jpg', true],
  ['baiser-balustrade-noir-et-blanc-palais-royal-paris-nathanael-charpentier.jpg', true],
  ['mariee-profil-galerie-palais-royal-paris-nathanael-charpentier.jpg', false],
  ['maries-colonnade-pont-bir-hakeim-paris-nathanael-charpentier.jpg', true],
  ['couple-banc-jardin-paris-nathanael-charpentier.jpg', false],
  ['maries-pont-bir-hakeim-tour-eiffel-paris-nathanael-charpentier.jpg', true],
  ['tendresse-banc-jardin-paris-nathanael-charpentier.jpg', false],
  ['baiser-pavillon-colbert-louvre-paris-nathanael-charpentier.jpg', false],
  ['maries-rochers-mer-domaine-murtoli-corse-nathanael-charpentier.jpg', false],
  ['maries-rochers-ciel-orage-plage-ramatuelle-saint-tropez-nathanael-charpentier.jpg', false],
  ['seance-jour-d-apres-vagues-deauville-nathanael-charpentier.jpg', true],
  ['mariee-silhouette-porte-fenetre-hotel-normandy-deauville-nathanael-charpentier.jpg', true],
  ['marie-porte-mariee-terrasse-coucher-de-soleil-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['mariee-terrasse-haie-lumiere-du-soir-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['baiser-mariee-portee-contre-jour-dore-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['portrait-mariee-lumiere-doree-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['profil-halo-lumiere-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['baiser-mains-visage-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['etreinte-voile-noir-et-blanc-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['detail-mains-robe-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['larmes-mariee-noir-et-blanc-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['rires-maries-jardins-coppelia-honfleur-nathanael-charpentier.jpg', true],
  ['marie-porte-mariee-plage-noir-et-blanc-santa-giulia-corse-nathanael-charpentier.jpg', false],
  ['detail-bouquet-mains-maries-chateau-champlatreux-nathanael-charpentier.jpg', false],
  ['mains-bouquet-noir-et-blanc-high-key-royan-nathanael-charpentier.jpg', false],
  ['baiser-cou-tatouage-noir-et-blanc-mariage-loiret-nathanael-charpentier.jpg', false],
  ['etreinte-maries-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['premiere-danse-chateau-la-bourdaisiere-nathanael-charpentier.jpg', true],
  ['danse-tendre-chateau-pont-chevron-ouzouer-sur-trezee-nathanael-charpentier.jpg', true],
  ['soiree-etreinte-piste-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['soiree-baiser-piste-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', false],
  ['invite-reflets-diner-chateau-saint-martin-du-tertre-nathanael-charpentier.jpg', false],
  ['marie-porte-fete-jardins-coppelia-honfleur-nathanael-charpentier.jpg', false],
  ['baiser-renverse-piste-verriere-chateau-pont-chevron-nathanael-charpentier.jpg', false],
  ['feu-d-artifice-maries-parc-chateau-champlatreux-nathanael-charpentier.jpg', true],
];

// 48 images. Les portraits d'artistes et le mineur restent hors de cette page.
export const ORDRE_PORTRAIT: [string, boolean][] = [
  ['portrait-art-ame-main-visage-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['portrait-art-ame-pensive-fond-peint-nathanael-charpentier.jpg', true],
  ['portrait-olivia-robe-rouge-mouvement-galerie-palais-royal-paris-nathanael-charpentier.jpg', true],
  ['portrait-maelle-menotti-art-ame-chesterfield-nathanael-charpentier.jpg', true],
  ['portrait-robe-noire-salon-chateau-de-villette-nathanael-charpentier.jpg', true],
  ['portrait-maelle-menotti-sequins-lumiere-fenetre-nathanael-charpentier.jpg', true],
  ['portrait-main-pudeur-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['portrait-art-ame-sourire-fond-peint-nathanael-charpentier.jpg', true],
  ['portrait-nikita-dj-voilage-fenetre-nathanael-charpentier.jpg', true],
  ['portrait-noir-et-blanc-regard-epaule-marseille-nathanael-charpentier.jpg', true],
  ['portrait-jade-fauteuil-cuir-lampe-industrielle-studio-gien-nathanael-charpentier.jpg', true],
  ['portrait-art-ame-miroir-rond-nathanael-charpentier.jpg', true],
  ['portrait-rire-chesterfield-mur-vert-nathanael-charpentier.jpg', true],
  ['portrait-art-ame-silhouette-fenetre-lampe-nathanael-charpentier.jpg', true],
  ['portrait-olivia-regard-clair-obscur-noir-et-blanc-nathanael-charpentier.jpg', false],
  ['detail-mains-croisees-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['portrait-homme-lin-drape-clair-nathanael-charpentier.jpg', true],
  ['portrait-cheveux-regard-baisse-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['portrait-robe-bleue-satin-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-art-ame-regard-leve-noir-et-blanc-nathanael-charpentier.jpg', true],
  ['portrait-jade-reflet-miroir-rond-beret-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-maelle-menotti-noir-et-blanc-scene-nathanael-charpentier.jpg', false],
  ['portrait-homme-chapeau-melon-studio-gien-nathanael-charpentier.jpg', true],
  ['portrait-art-ame-lumiere-laterale-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-olivia-robe-blanche-colonnes-palais-royal-paris-nathanael-charpentier.jpg', true],
  ['portrait-profil-penombre-nathanael-charpentier.jpg', true],
  ['portrait-justine-bourrelier-mains-visage-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-jade-allongee-chesterfield-cocktail-studio-gien-nathanael-charpentier.jpg', true],
  ['portrait-noir-et-blanc-ombre-mur-studio-gien-nathanael-charpentier.jpg', false],
  ['detail-main-bracelets-portrait-art-ame-nathanael-charpentier.jpg', false],
  ['portrait-jade-lecture-fenetre-rue-noir-et-blanc-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-justine-bourrelier-costume-sombre-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-olivia-profil-sourire-coulisses-paris-nathanael-charpentier.jpg', false],
  ['portrait-homme-exterieur-brique-portail-nathanael-charpentier.jpg', false],
  ['portrait-jade-beret-chesterfield-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-art-ame-larme-essuyee-nathanael-charpentier.jpg', false],
  ['portrait-olivia-robe-blanche-mouvement-colonnade-palais-royal-paris-nathanael-charpentier.jpg', false],
  ['portrait-tabouret-fond-clair-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-justine-bourrelier-drape-ivoire-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-jade-chesterfield-vinyles-ambiance-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-olivia-maquillage-levres-coulisses-noir-et-blanc-nathanael-charpentier.jpg', false],
  ['portrait-armonie-noury-miss-loiret-noir-et-blanc-nathanael-charpentier.jpg', false],
  ['robe-blanche-mouvement-escalier-noir-et-blanc-nathanael-charpentier.jpg', false],
  ['portrait-jade-profil-beret-mur-vert-studio-gien-nathanael-charpentier.jpg', false],
  ['portrait-justine-bourrelier-robe-studio-gien-nathanael-charpentier.jpg', false],
  ['detail-main-penombre-portrait-nathanael-charpentier.jpg', false],
  ['portrait-olivia-robe-blanche-colonne-noir-et-blanc-palais-royal-paris-nathanael-charpentier.jpg', false],
  ['portrait-olivia-robe-rouge-dentelle-grilles-palais-royal-paris-nathanael-charpentier.jpg', false],
];

export const fichiers = (ordre: [string, boolean][]) => ordre.map(([f]) => f);
